Devnet
ArkEcosystem/ark-node pull request #74
Opened 2018-06-04 15:22 UTC by fix

2018-06-07 07:57 UTC, zillionn requested changes

2018-06-07 07:57 UTC, zillionn commented on modules/delegates.js
> +		router.get('/forging/status', function (req, res) {
This should be outside of `if (process.env.DEBUG) {`

2018-06-07 08:09 UTC, fix commented on modules/delegates.js
> +		router.get('/forging/status', function (req, res) {
no will keep outside, for security reason the time to switch to v2

2018-06-07 08:10 UTC, zillionn commented on modules/delegates.js
> +		router.get('/forging/status', function (req, res) {
I'm talking about only "/forging/status".

2018-06-08 06:03 UTC, faustbrian commented on modules/delegates.js
> +		router.get('/forging/status', function (req, res) {
@zillionn I would assume you want to move this outside because of the ARKcommander no longer being able to show the forging status?

2018-06-08 13:16 UTC, zillionn commented on modules/delegates.js
> +		router.get('/forging/status', function (req, res) {
Yes, one of the reasons. It just shows the status, you can't enable/disable it.

2018-08-28 05:19 UTC, closed without merging